# Development stack overrides
#
# Variables are populated with values from `.env`
#
version: '2'
services:
  php:
    build:
      context: .
      # FLAVOUR can be undefinied OR -debian
      # undefined == alpine base image
      # -debian   == debian base image
      dockerfile: Dockerfile${FLAVOUR}
    ports:
      - 29680:80
    depends_on:
      - db
      - mailcatcher
      - redis
    environment:
      - DB_ENV_MYSQL_ROOT_PASSWORD=secret
      # For host-volume development (permissions)
      - PHP_USER_ID=82
      # For composer usage in container
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      # local dev mail setup
      #- APP_ADMIN_EMAIL=${APP_ADMIN_EMAIL}
      - APP_MAILER_HOST=mailcatcher
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./composer.json:/app/composer.json:cached
      - ./composer.lock:/app/composer.lock:cached
      - ./config:/app/config
      - ./src:/app/src
      - ./vendor/:/app/vendor

  db:
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    image: percona:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - '3306'
  mailcatcher:
    image: nisenabe/mailcatcher
    ports:
      - '1080'